
import React, { useState } from 'react';
import { Language } from '../../types';

interface OnboardingModalProps {
  onComplete: () => void;
  setLang: (lang: Language) => void;
}

const tourSteps = [
    {
        icon: '📖',
        title: 'Learn Stories',
        description: 'Read new stories generated by AI. Long-press any word to see its translation in your native language.'
    },
    {
        icon: '⌨️',
        title: 'Practice Typing',
        description: 'Improve your typing speed and accuracy by typing the stories you read.'
    },
    {
        icon: '🔊',
        title: 'Practice Pronunciation',
        description: 'Read the stories aloud and get instant feedback on your pronunciation.'
    },
    {
        icon: '🤖',
        title: 'Meet LiftBot',
        description: 'Have any doubts? Ask your personal AI English tutor any question about grammar, vocabulary, or the app itself.'
    }
];


const OnboardingModal: React.FC<OnboardingModalProps> = ({ onComplete, setLang }) => {
    const [step, setStep] = useState(1);

    const handleLanguageSelect = (lang: Language) => {
        setLang(lang);
        setStep(2);
    };

    return (
        <div className="fixed inset-0 bg-black/50 z-50 flex justify-center items-center p-4">
            <div className="bg-slate-50 rounded-2xl p-6 w-full max-w-md text-center">
                {step === 1 && (
                    <div>
                        <h2 className="text-2xl font-bold text-slate-800 mt-0">Welcome to AI English Tutor!</h2>
                        <p className="text-slate-600">To get started, please select your mother tongue.</p>
                        <div className="flex flex-col sm:flex-row gap-4 justify-center mt-6">
                            <button className="px-6 py-4 text-lg font-semibold text-white bg-teal-600 rounded-lg hover:bg-teal-700 transition" onClick={() => handleLanguageSelect('hi')}>हिन्दी (Hindi)</button>
                            <button className="px-6 py-4 text-lg font-semibold text-white bg-teal-600 rounded-lg hover:bg-teal-700 transition" onClick={() => handleLanguageSelect('te')}>తెలుగు (Telugu)</button>
                        </div>
                    </div>
                )}
                {step > 1 && step <= tourSteps.length + 1 && (
                    <div>
                        <div className="text-6xl mb-4">{tourSteps[step - 2].icon}</div>
                        <h3 className="text-xl font-bold text-slate-800 mt-0">{tourSteps[step - 2].title}</h3>
                        <p className="text-slate-600">{tourSteps[step - 2].description}</p>
                        <div className="mt-6">
                            {step <= tourSteps.length ? (
                                <button className="px-5 py-2.5 font-semibold text-white bg-teal-600 rounded-lg hover:bg-teal-700 transition" onClick={() => setStep(s => s + 1)}>Next</button>
                            ) : (
                                <button className="px-5 py-2.5 font-semibold text-white bg-teal-600 rounded-lg hover:bg-teal-700 transition" onClick={onComplete}>Start Learning!</button>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default OnboardingModal;